name: Deploy

on:
  cron: '5 23 * * 0' # 08:05(Mon) JST
  workflow_dispatch:

jobs:
  curl:
    name: Kick deploy hook
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: curl -X POST '${{ secrets.DEPLOY_HOOK_URL }}'

  purge_cache:
    name: Purge Cloudflare Cache
    runs-on: ubuntu-latest
    needs: curl
    steps:
      - name: Wait for 2 minutes
        run: sleep 150
      - name: Purge Cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
